### ISSUE TITLE
Need change in order profile

### ISSUE THREAD

**Issue by ppreethi89** [jerryaoverton/fedex-economy-market#1]
The order profile should have below fields from UI. Main changes is to add new field called delivery_provider to identify who should deliver it..delivery_address and shipment_weight to check which drone can pick it up. If schema change is not possible, we can agree on common format for it.

order_example = {'supplier': '123abc',
                 'customer': '456xyz',
                 'payment_method': 'tokens',
                 'price': 100,
                 'delivery_provider': 'Drone',
                 'order_details': 'description:charge the drone to 100%,shipment_weight:3',
                 'delivery_address':'3600 Lancaster avenue, Philadelphia, 19104',
                 'terms_and_conditions': 'must not harm drone',
                 'status': 'complete',
                 'status_date': '08/05/2020'
                 }

**Comment by sa3664** [comment]
Completed
