### ISSUE TITLE
Need Service Provider Profile

### ISSUE THREAD

**Issue by ppreethi89** [jerryaoverton/fedex-economy-market#2]
For service provider profile, i need some parameters to define
type of service-  Drone maintenance/ Drone charging/Drone purchasing, etc....i am only interested in Drone maintenance, Drone charging- 
then cost for service- the amount in FexCoins -  
the address of service provider. 

highlighted are important fields, rest should be as per your convenience

profile_example_ServiceProvider = {'first_name': 'XXXX',
                   'last_name': 'XXXX',
                   **'RegistrationType': 'ServiceProvider',**
                   'email': 'imb@gmail.com',
                   'area_code': '6',
		               'phone': '897897987',
                   **'ServiceType': 'DroneMaintenance',
                   'ServiceFee':'50'
                   'address': 'xyz'**
		               'image_url': 'www.pic.com/profile.jpg',
                   'profile_url': 'website_url?userid=imb@gmm',
                   'description': 'A great and powerful Food Business',
                   'tags': 'ServiceProvider',
                   'rating': 4,
                   'status': 'active'
                   }

**Comment by sa3664** [comment]
Completed.
