### ISSUE TITLE
Change of schema in General Profile

### ISSUE THREAD

**Issue by ppreethi89** [jerryaoverton/fedex-economy-market#4]
profile={'first_name': 'Drone',
                            'last_name': '',
                            'RegistrationType': 'Drone Service',
                            'email':'',
                            'BusinessType':'',
                            **'street': '3600 Lancaster Avenue',
                            'city':'Philadelphia',
                            'stateorprovince':'PA',
                            'postalcode':'19104',
                            'countrycode':'US',**
                            'area_code': '267',
                            'phone': '897897987',
                            'image_url': 'www.pic.com/profile.jpg',
                            'profile_url': 'https://fedex-economy-drone.herokuapp.com/Drone_Info',
                            'description': 'A very useful drone',
                            'tags': 'drone, delivery',
                            'rating': 4,
                            'status': 'idle',
                            'properties':'type:Quadcopter,capacity_lbs:'+str(randint(3,5))+',flyduration_min:10'
                   }

**Comment by sa3664** [comment]
Completed .
